import type { Machine, ProductionData, BradeProduct, Alert, Task } from "./types"

export const mockMachines: Machine[] = [
  {
    id: "M001",
    name: "Spinning Machine A1",
    stage: "spinning",
    status: "operational",
    floorId: "F1",
    lastUpdated: new Date(),
    runtime: 480,
    downtime: 20,
  },
  {
    id: "M002",
    name: "Spinning Machine A2",
    stage: "spinning",
    status: "operational",
    floorId: "F1",
    lastUpdated: new Date(),
    runtime: 450,
    downtime: 50,
  },
  {
    id: "M003",
    name: "Weaving Machine B1",
    stage: "weaving",
    status: "delay",
    floorId: "F1",
    lastUpdated: new Date(),
    runtime: 420,
    downtime: 80,
  },
  {
    id: "M004",
    name: "Dyeing Machine C1",
    stage: "dyeing",
    status: "operational",
    floorId: "F2",
    lastUpdated: new Date(),
    runtime: 500,
    downtime: 0,
  },
  {
    id: "M005",
    name: "Finishing Machine D1",
    stage: "finishing",
    status: "fault",
    floorId: "F2",
    lastUpdated: new Date(),
    runtime: 300,
    downtime: 200,
  },
]

export const mockProductionData: ProductionData[] = [
  {
    id: "P001",
    machineId: "M001",
    timestamp: new Date(),
    outputUnits: 150,
    qualityScore: 95,
    defectCount: 2,
    bGradeCount: 1,
  },
  {
    id: "P002",
    machineId: "M002",
    timestamp: new Date(),
    outputUnits: 145,
    qualityScore: 92,
    defectCount: 5,
    bGradeCount: 2,
  },
  {
    id: "P003",
    machineId: "M003",
    timestamp: new Date(),
    outputUnits: 120,
    qualityScore: 88,
    defectCount: 8,
    bGradeCount: 3,
  },
]

export const mockBGradeProducts: BradeProduct[] = [
  {
    id: "BG001",
    machineId: "M001",
    batchId: "BATCH001",
    defectType: "weaving_fault",
    severity: "medium",
    location: "center",
    timestamp: new Date(Date.now() - 3600000),
    qcStaffId: "4",
    notes: "Loose thread detected",
  },
  {
    id: "BG002",
    machineId: "M003",
    batchId: "BATCH002",
    defectType: "dye_issue",
    severity: "high",
    location: "edge",
    timestamp: new Date(Date.now() - 7200000),
    qcStaffId: "4",
    notes: "Uneven dye coloration",
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "A001",
    type: "bottleneck",
    machineId: "M003",
    message: "Weaving Machine B1 exceeds time limit",
    severity: "high",
    timestamp: new Date(Date.now() - 1800000),
    resolved: false,
  },
  {
    id: "A002",
    type: "fault",
    machineId: "M005",
    message: "Finishing Machine D1 fault detected",
    severity: "high",
    timestamp: new Date(Date.now() - 3600000),
    resolved: false,
  },
]

export const mockTasks: Task[] = [
  {
    id: "T001",
    operatorId: "1",
    machineId: "M001",
    startTime: new Date(Date.now() + 3600000),
    endTime: new Date(Date.now() + 7200000),
    status: "pending" as const,
    description: "Spinning batch A1-001",
  },
  {
    id: "T002",
    operatorId: "1",
    machineId: "M002",
    startTime: new Date(Date.now() + 7200000),
    endTime: new Date(Date.now() + 10800000),
    status: "in_progress" as const,
    description: "Spinning batch A2-002",
  },
  {
    id: "T003",
    operatorId: "2",
    machineId: "M003",
    startTime: new Date(Date.now()),
    endTime: new Date(Date.now() + 3600000),
    status: "in_progress" as const,
    description: "Weaving batch B1-001",
  },
  {
    id: "T004",
    operatorId: "2",
    machineId: "M004",
    startTime: new Date(Date.now() + 10800000),
    endTime: new Date(Date.now() + 14400000),
    status: "pending" as const,
    description: "Dyeing batch C1-001",
  },
]
